language: julia

os:
  - linux

julia:
  - 0.7

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.add("Documenter"); include("make.jl")'
